import Link from "next/link";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { listDealerApplications } from "@/features/dealers/admin";
import { getActiveAdmin } from "@/lib/auth/admin";

function label(status: string) { return status === "new" ? "Pending" : status[0].toUpperCase() + status.slice(1); }

export default async function DealerApplicationsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  if (!(await getActiveAdmin())) redirect("/admin/login");
  const input = await searchParams;
  const data = await listDealerApplications(input);
  return <main className="mx-auto max-w-6xl p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Dealer applications</h1><p className="mt-1 text-sm text-[color:var(--muted)]">Review prospective WoodBay dealers and keep public visibility deliberate.</p></div><Link href="/dealers/become-a-dealer" className="text-sm text-[color:var(--gold)] underline underline-offset-4">Public application form</Link></div><form className="mt-8 flex flex-col gap-3 sm:flex-row"><input name="q" defaultValue={data.q} placeholder="Search business, contact or phone" className="min-h-11 flex-1 border border-[color:var(--border-dark)] bg-transparent px-3"/><select name="status" defaultValue={data.status} className="min-h-11 border border-[color:var(--border-dark)] bg-transparent px-3 sm:w-44"><option value="all">All</option><option value="new">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><Button variant="light">Search</Button></form><div className="mt-8 space-y-3 md:hidden">{data.rows.map((row) => <Link key={row.id} href={`/admin/dealers/${row.id}`} className="block border border-[color:var(--border-dark)] p-4"><b>{row.businessName}</b><p className="mt-1 text-sm">{row.contactPerson} · {row.phone}</p><p className="mt-2 text-sm text-[color:var(--muted)]">{row.location}, {row.state} · {label(row.status)}</p></Link>)}{data.rows.length === 0 && <p className="py-12 text-center text-sm text-[color:var(--muted)]">No applications found.</p>}</div><div className="mt-8 hidden md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[color:var(--border-dark)] text-xs uppercase tracking-[.12em] text-[color:var(--muted)]"><th className="py-3">Business</th><th>Contact</th><th>Phone</th><th>Location</th><th>Submitted</th><th>Status</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-b border-[color:var(--border-dark)]"><td className="py-4"><Link href={`/admin/dealers/${row.id}`}>{row.businessName}</Link></td><td>{row.contactPerson}</td><td>{row.phone}</td><td>{row.location}, {row.state}</td><td>{new Date(row.createdAt).toLocaleDateString()}</td><td>{label(row.status)}</td></tr>)}</tbody></table>{data.rows.length === 0 && <p className="py-12 text-center text-sm text-[color:var(--muted)]">No applications found.</p>}</div></main>;
}
