import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Search, SlidersHorizontal } from "lucide-react";
import { primaryImage, productDetailPath } from "../data/catalogue";
import type { CatalogueCategory, CatalogueProduct } from "../types";
import { Button } from "@/components/ui/button";
export function ProductCard({ product }: { product: CatalogueProduct }) { const image = primaryImage(product); return <article className="group overflow-hidden border border-[color:var(--border-dark)] bg-[color:var(--surface-dark)] text-[color:var(--foreground-light)]"><div className="relative aspect-[4/3] bg-[radial-gradient(circle_at_50%_20%,#48483f,transparent_68%),#252620]">{image ? <Image src={image.storage_key} alt={image.alt_text ?? `${product.name} by Woodbay`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-cover transition duration-500 group-hover:scale-[1.03]" /> : <div className="grid h-full place-items-center"><span className="font-display text-3xl tracking-[.12em] text-[color:var(--gold)]">WOODBAY</span></div>}</div><div className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[color:var(--gold)]">{product.category?.name ?? "Woodbay Collection"}</p><h3 className="font-display mt-3 text-3xl leading-none">{product.name}</h3>{product.short_description && <p className="mt-3 line-clamp-2 text-sm leading-6 text-[color:var(--muted)]">{product.short_description}</p>}<Link href={productDetailPath(product)} className="mt-6 inline-flex min-h-11 items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-[color:var(--gold)]">View Product <ArrowRight size={15} /></Link></div></article>; }
export function CategoryChips({ categories, active, basePath }: { categories: CatalogueCategory[]; active: string | null; basePath: string }) { return <nav aria-label="Subcategories" className="-mx-5 flex snap-x gap-2 overflow-x-auto px-5 pb-2 md:mx-0 md:px-0">{categories.map((category) => <Link key={category.id} href={active === category.slug ? basePath : `${basePath}?subcategory=${category.slug}`} aria-current={active === category.slug ? "page" : undefined} className={`min-h-11 shrink-0 snap-start border px-4 py-3 text-xs font-bold uppercase tracking-[.1em] ${active === category.slug ? "border-[color:var(--gold)] bg-[color:var(--gold)] text-[color:var(--background-dark)]" : "border-[color:var(--border-dark)] text-[color:var(--foreground-light)] hover:border-[color:var(--gold)]"}`}>{category.name}</Link>)}</nav>; }
export function CatalogueControls({ path, q, subcategory, sort, categories }: { path: string; q: string; subcategory: string | null; sort: string; categories: CatalogueCategory[] }) { return <form action={path} className="grid gap-3 border-y border-[color:var(--border-dark)] py-5 md:grid-cols-[1fr_auto_auto]"><label className="relative"><span className="sr-only">Search products</span><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[color:var(--gold)]" /><input name="q" defaultValue={q} placeholder="Search products or product code" className="min-h-11 w-full border border-[color:var(--border-dark)] bg-transparent pl-11 pr-4 text-sm text-[color:var(--foreground-light)] outline-none placeholder:text-[#85847d] focus:border-[color:var(--gold)]" /></label><label className="flex min-h-11 items-center gap-2 border border-[color:var(--border-dark)] px-3 text-xs text-[color:var(--foreground-light)]"><SlidersHorizontal size={15} className="text-[color:var(--gold)]" /><span className="sr-only">Filter by subcategory</span><select name="subcategory" defaultValue={subcategory ?? ""} className="bg-transparent outline-none"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.slug}>{category.name}</option>)}</select></label><select aria-label="Sort products" name="sort" defaultValue={sort} className="min-h-11 border border-[color:var(--border-dark)] bg-transparent px-3 text-xs text-[color:var(--foreground-light)] outline-none"><option value="default">Recommended</option><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option></select><input type="hidden" name="page" value="1" /><Button type="submit" className="md:col-start-3">Apply filters</Button></form>; }
export function EmptyProducts({ path }: { path: string }) { return <div className="border border-[color:var(--border-gold)] bg-[color:var(--surface-dark)] px-6 py-14 text-center"><p className="font-display text-4xl">No products found in this selection.</p><p className="mt-4 text-sm text-[color:var(--muted)]">Try another category or clear your search.</p><Link href={path} className="mt-7 inline-block"><Button>Browse all products</Button></Link></div>; }
export function Pagination({ path, page, pageCount, q, subcategory, sort }: { path: string; page: number; pageCount: number; q: string; subcategory: string | null; sort: string }) { if (pageCount <= 1) return null; const href = (target: number) => { const params = new URLSearchParams({ page: String(target) }); if (q) params.set("q", q); if (subcategory) params.set("subcategory", subcategory); if (sort !== "default") params.set("sort", sort); return `${path}?${params}`; }; return <nav aria-label="Product pages" className="mt-10 flex items-center justify-center gap-3"><Link aria-disabled={page === 1} className="min-h-11 border border-[color:var(--border-dark)] px-4 py-3 text-xs uppercase tracking-[.1em] disabled:opacity-40" href={page === 1 ? path : href(page - 1)}>Previous</Link><span className="text-sm text-[color:var(--muted)]">Page {page} of {pageCount}</span><Link aria-disabled={page === pageCount} className="min-h-11 border border-[color:var(--border-dark)] px-4 py-3 text-xs uppercase tracking-[.1em]" href={page === pageCount ? path : href(page + 1)}>Next</Link></nav>; }
