import { notFound, redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { getDealerApplication, updateDealerApplicationNote } from "@/features/dealers/admin";
import { DealerDeleteAction } from "@/features/dealers/components/dealer-delete-action";
import { DealerApplicationEditForm } from "@/features/dealers/components/dealer-application-edit-form";
import { DealerEditForm } from "@/features/dealers/components/dealer-edit-form";
import { DealerReviewActions } from "@/features/dealers/components/dealer-review-actions";
import { getActiveAdmin } from "@/lib/auth/admin";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  if (!(await getActiveAdmin())) redirect("/admin/login");
  let data;
  try { data = await getDealerApplication((await params).id); } catch { notFound(); }
  const { application, dealer, audit } = data;
  return <main className="mx-auto max-w-5xl p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.14em] text-[color:var(--gold)]">Dealer application</p><h1 className="mt-2 text-3xl font-semibold">{application.business_name}</h1><p className="mt-2 text-sm text-[color:var(--muted)]">{application.status === "new" ? "Pending" : application.status} · Submitted {new Date(application.created_at).toLocaleDateString()}</p></div><DealerDeleteAction id={application.id} /></div>
    <DealerReviewActions id={application.id} status={application.status} dealerId={application.dealer_id} />
    <section className="mt-8 border p-5"><h2 className="text-xl font-semibold">Application details</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[color:var(--muted)]">Applicant</dt><dd>{application.contact_person}</dd></div><div><dt className="text-[color:var(--muted)]">Phone</dt><dd>{application.phone}</dd></div><div><dt className="text-[color:var(--muted)]">WhatsApp</dt><dd>{application.whatsapp ?? application.phone}</dd></div><div><dt className="text-[color:var(--muted)]">Email</dt><dd>{application.email ?? "—"}</dd></div><div><dt className="text-[color:var(--muted)]">Business type</dt><dd>{application.business_type ?? "—"}</dd></div><div><dt className="text-[color:var(--muted)]">Years in business</dt><dd>{application.years_in_business ?? "—"}</dd></div><div><dt className="text-[color:var(--muted)]">Existing showroom</dt><dd>{application.has_showroom == null ? "—" : application.has_showroom ? "Yes" : "No"}</dd></div><div><dt className="text-[color:var(--muted)]">Areas served</dt><dd>{application.areas_served ?? "—"}</dd></div><div className="sm:col-span-2"><dt className="text-[color:var(--muted)]">Location</dt><dd>{application.location}, {application.district}, {application.state}<br />{application.address ?? "—"}</dd></div><div className="sm:col-span-2"><dt className="text-[color:var(--muted)]">Product interests</dt><dd>{application.product_interests?.join(" · ") || "—"}</dd></div><div className="sm:col-span-2"><dt className="text-[color:var(--muted)]">Message</dt><dd>{application.message ?? "—"}</dd></div><div><dt className="text-[color:var(--muted)]">Submitted</dt><dd>{new Date(application.created_at).toLocaleString()}</dd></div><div><dt className="text-[color:var(--muted)]">Last updated</dt><dd>{new Date(application.updated_at).toLocaleString()}</dd></div></dl></section>
    <section className="mt-8 border p-5"><h2 className="text-xl font-semibold">Internal note</h2><form action={updateDealerApplicationNote} className="mt-4 grid gap-3"><input type="hidden" name="id" value={application.id} /><textarea name="admin_notes" defaultValue={application.admin_notes ?? ""} rows={4} maxLength={1000} className="w-full border p-3" /><Button className="sm:w-fit">Save note</Button></form></section>
    {dealer ? <section className="mt-8 border p-5"><h2 className="text-xl font-semibold">Public dealer profile</h2><p className="mt-1 text-sm text-[color:var(--muted)]">Edit the canonical dealer record used by the public locator.</p><div className="mt-6"><DealerEditForm dealer={dealer} /></div></section> : <section className="mt-8 border p-5"><h2 className="text-xl font-semibold">Edit pending application</h2><DealerApplicationEditForm application={application} /></section>}
    <section className="mt-8 border p-5"><h2 className="text-xl font-semibold">Activity history</h2><ol className="mt-5 space-y-3 text-sm">{audit.map((event) => <li key={`${event.created_at}-${event.action}`} className="border-t pt-3"><b>{event.action.replaceAll("_", " ")}</b>{event.from_status || event.to_status ? <span> · {event.from_status ?? "—"} → {event.to_status ?? "—"}</span> : null}<time className="mt-1 block text-[color:var(--muted)]">{new Date(event.created_at).toLocaleString()}</time></li>)}</ol></section>
  </main>;
}
