import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CTASection, Container, PageHero, Section } from "@/components/layout/primitives";
import { CatalogueControls, CategoryChips, EmptyProducts, Pagination, ProductCard } from "@/features/products/components/catalogue-ui";
import { getCategoryBySlug, getChildCategories, getProducts, parseCatalogueParams } from "@/features/products/data/catalogue";
import type { CatalogueCategory, CatalogueProduct } from "@/features/products/types";
export const dynamic = "force-dynamic";
const image = "/images/preview/woodbay-kitchen-preview.png";
export async function generateMetadata({ params }: { params: Promise<{ categorySlug: string }> }): Promise<Metadata> { const { categorySlug } = await params; const category = await getCategoryBySlug(categorySlug); if (!category) return {}; return { title: `${category.name} | Woodbay`, description: category.description ?? `Explore Woodbay ${category.name.toLowerCase()} and related product ranges.` }; }
export default async function CategoryPage({ params, searchParams }: { params: Promise<{ categorySlug: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const { categorySlug } = await params; const category = await getCategoryBySlug(categorySlug); if (!category || category.parent_id) notFound(); const parsed = parseCatalogueParams(await searchParams); let children: CatalogueCategory[] = []; let result: { products: CatalogueProduct[]; count: number; pageCount: number } = { products: [], count: 0, pageCount: 1 }; let failed = false; try { children = await getChildCategories(category.id); result = await getProducts(category, children, parsed); } catch { failed = true; } const path = `/products/${category.slug}`; return <><PageHero eyebrow="Woodbay Products" title={category.name} description={category.description ?? "Explore the Woodbay product range."} image={image} breadcrumb={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: category.name }]} /><Section tone="dark"><Container>{children.length > 0 && <><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[color:var(--gold)]">Explore product groups</p><div className="mt-4"><CategoryChips categories={children} active={parsed.subcategory} basePath={path} /></div></>}<div className="mt-10"><CatalogueControls path={path} q={parsed.q} subcategory={parsed.subcategory} sort={parsed.sort} categories={children} /></div><div className="mt-7 flex items-center justify-between gap-4"><p className="text-sm text-[color:var(--muted)]">{result.count === 0 ? "No published products" : `Showing ${(parsed.page - 1) * 12 + 1}–${Math.min(parsed.page * 12, result.count)} of ${result.count} products`}</p></div>{failed ? <div className="mt-8 border border-[color:var(--border-gold)] p-8 text-sm text-[color:var(--muted)]">The catalogue could not be loaded right now. Please try again shortly.</div> : result.products.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{result.products.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="mt-8"><EmptyProducts path={path} /></div>}<Pagination path={path} page={parsed.page} pageCount={result.pageCount} q={parsed.q} subcategory={parsed.subcategory} sort={parsed.sort} /></Container></Section><CTASection title="Looking for Woodbay products near you?" description="Connect with an authorised Woodbay accessories dealer or contact our team for assistance." action={{ label: "Find a Dealer", href: "/dealers" }} /></>; }
