import Image from "next/image";
import Link from "next/link";
import { ArrowRight, type LucideIcon } from "lucide-react";
import { Button, type ButtonVariant } from "@/components/ui/button";
export function Container({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`mx-auto w-full max-w-[1440px] px-5 md:px-8 xl:px-14 ${className}`}>{children}</div>; }
export function Section({ children, tone = "dark", className = "" }: { children: React.ReactNode; tone?: "dark" | "light"; className?: string }) { return <section className={`py-16 md:py-20 lg:py-28 ${tone === "dark" ? "bg-[color:var(--background-dark)] text-[color:var(--foreground-light)]" : "bg-[color:var(--surface-light)] text-[color:var(--foreground-dark)]"} ${className}`}>{children}</section>; }
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-[10px] font-bold uppercase tracking-[.2em] text-[color:var(--gold)]">{children}</p>; }
export function SectionHeader({ eyebrow, title, description, align = "left" }: { eyebrow?: string; title: string; description?: string; align?: "left" | "center" }) { return <div className={align === "center" ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}>{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h2 className="font-display mt-3 text-4xl leading-none sm:text-5xl">{title}</h2>{description && <p className="mt-5 text-sm leading-7 text-[color:var(--muted-dark)] dark:text-[color:var(--muted)]">{description}</p>}</div>; }
export function Divider() { return <div className="h-px w-full bg-[color:var(--border-gold)]" />; }
export function FeatureItem({ icon: Icon, title, children }: { icon: LucideIcon; title: string; children: React.ReactNode }) { return <div className="border-t border-[color:var(--border-gold)] py-6"><Icon size={21} strokeWidth={1.25} className="text-[color:var(--gold)]" /><h3 className="mt-5 text-sm font-bold uppercase tracking-[.12em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[color:var(--muted)]">{children}</p></div>; }
export function StatItem({ value, label }: { value: string; label: string }) { return <div className="border-l border-[color:var(--border-gold)] pl-5"><p className="font-display text-4xl text-[color:var(--gold)] sm:text-5xl">{value}</p><p className="mt-2 max-w-36 text-xs uppercase leading-5 tracking-[.1em] text-[color:var(--muted)]">{label}</p></div>; }
export function ImageCard({ src, alt, children, className = "" }: { src: string; alt: string; children?: React.ReactNode; className?: string }) { return <div className={`group relative overflow-hidden border border-[color:var(--border-dark)] ${className}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-500 group-hover:scale-[1.03]" />{children && <div className="relative z-10 flex min-h-72 items-end bg-gradient-to-t from-black/70 via-black/0 to-transparent p-6">{children}</div>}</div>; }
export function ProductCategoryCard({ title, href, image, eyebrow, description, tone = "dark" }: { title: string; href: string; image: string; eyebrow?: string; description?: string; tone?: "dark" | "light" }) { const dark = tone === "dark"; return <Link href={href} className={`group block overflow-hidden border ${dark ? "border-[color:var(--border-dark)] bg-[color:var(--surface-dark)] text-[color:var(--foreground-light)]" : "border-[#d4ccbe] bg-white text-[color:var(--foreground-dark)]"}`}><div className="relative aspect-[4/3] overflow-hidden"><Image src={image} alt="" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.03]" /></div><div className="p-6">{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<div className="mt-2 flex items-center justify-between gap-3"><h3 className="font-display text-3xl leading-none">{title}</h3><ArrowRight size={20} className="shrink-0 text-[color:var(--gold)] transition-transform group-hover:translate-x-1" strokeWidth={1.25} /></div>{description && <p className={`mt-3 text-sm leading-6 ${dark ? "text-[color:var(--muted)]" : "text-[color:var(--muted-dark)]"}`}>{description}</p>}</div></Link>; }
export function Breadcrumb({ items }: { items: readonly { label: string; href?: string }[] }) { return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap gap-2 text-xs text-[#c6c0b5]">{items.map((item, index) => <li key={item.label} className="flex items-center gap-2">{index > 0 && <span aria-hidden="true" className="text-[color:var(--gold)]">/</span>}{item.href ? <Link href={item.href} className="hover:text-[color:var(--gold)]">{item.label}</Link> : <span aria-current="page">{item.label}</span>}</li>)}</ol></nav>; }
export function PageHero({ eyebrow, title, description, image, breadcrumb, cta }: { eyebrow?: string; title: string; description?: string; image?: string; breadcrumb?: readonly { label: string; href?: string }[]; cta?: { label: string; href: string; variant?: ButtonVariant } }) { return <section className="relative isolate overflow-hidden bg-[color:var(--background-deep)] text-[color:var(--foreground-light)]">{image && <Image src={image} alt="" fill priority sizes="100vw" className="z-0 object-cover opacity-40" />}<div className="absolute inset-0 z-10 bg-black/50" /><Container className="relative z-20 py-20 md:py-28 lg:py-36">{breadcrumb && <Breadcrumb items={breadcrumb} />}<div className="mt-14 max-w-3xl">{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h1 className="font-display mt-4 text-5xl leading-[.92] sm:text-6xl lg:text-7xl">{title}</h1>{description && <p className="mt-6 max-w-xl text-base leading-7 text-[#d3cec5]">{description}</p>}{cta && <Link href={cta.href} className="mt-8 inline-block"><Button variant={cta.variant}>{cta.label}<ArrowRight size={15} /></Button></Link>}</div></Container></section>; }
export function CTASection({ title, description, action }: { title: string; description: string; action: { label: string; href: string } }) { return <Section tone="dark"><Container><div className="border-y border-[color:var(--border-gold)] py-12 text-center"><Eyebrow>Woodbay</Eyebrow><h2 className="font-display mt-4 text-4xl sm:text-5xl">{title}</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-[color:var(--muted)]">{description}</p><Link href={action.href} className="mt-7 inline-block"><Button>{action.label}<ArrowRight size={15} /></Button></Link></div></Container></Section>; }
