export const about = {
  assets: { hero: "/images/homepage/manufacturing-preview.png", story: "/images/preview/woodbay-kitchen-preview.png", manufacturing: "/images/homepage/manufacturing-preview.png", interiors: "/images/homepage/furniture-decor-preview.png", founderPortrait: null as string | null },
  intro: { title: "Creating Better Spaces\nThrough Better Details.", paragraphs: ["Woodbay brings together premium kitchen accessories, wardrobe solutions, furniture, smart products and decor-led interior solutions for contemporary living.", "Our approach balances thoughtful design with practical function, dependable performance and a commitment to value—so each product earns its place in the spaces people use every day."] },
  values: [{ title: "Premium Quality", description: "Considered materials and details selected for confident everyday use." }, { title: "Innovative Design", description: "Better ways to organise, move and experience the home." }, { title: "Trusted Performance", description: "Reliable solutions designed around lasting function." }, { title: "Affordable Solutions", description: "Premium thinking made more accessible to more spaces." }],
  founder: { name: "Ansar A", role: "Founder & Managing Director", title: "A Vision Built Around\nQuality & Innovation.", message: "Woodbay is guided by a simple principle: make thoughtful design, reliable performance and useful innovation accessible to every space we serve." },
  vision: "To shape better living environments through thoughtful interior solutions that combine design, functionality and enduring value.",
  mission: "To develop and deliver considered kitchen, wardrobe, furniture, smart and decor solutions with quality, innovation and service at their core.",
  divisions: [{ title: "Kitchen Accessories", href: "/products/kitchen-accessories", description: "Functional systems for modern kitchens." }, { title: "Wardrobe Accessories", href: "/products/wardrobe-accessories", description: "Organised interiors with intuitive access." }, { title: "Smart Products", href: "/products/smart-products", description: "Modern innovation for everyday spaces." }, { title: "Decor & Interior Solutions", href: "/products/decor", description: "Surfaces and finishes with visual character." }],
  process: ["Design", "Material", "Production", "Quality Check", "Delivery"],
  journey: [{ title: "A Focus on Better Hardware", text: "A starting point in practical, elevated details for the home." }, { title: "Expanding the Product Range", text: "Growing into broader kitchen and wardrobe solutions." }, { title: "Smart & Interior Solutions", text: "Bringing new possibilities to contemporary spaces." }, { title: "Furniture & Factory-Direct Experiences", text: "Connecting considered interiors with direct consultation." }],
  whyChoose: ["Carefully Selected Product Range", "Contemporary Design", "Reliable Performance", "Practical Solutions", "Dealer Support", "Customer-Focused Service"],
  locations: [{ title: "Factory", detail: "Factory location and address to be announced." }, { title: "Office", detail: "Office location and address to be announced." }],
  // Replace preview assets and the monogram treatment with approved Woodbay media before launch.
} as const;
