"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getActiveAdmin } from "@/lib/auth/admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { escapeCsvValue } from "@/features/vouchers/admin-utils";
const factoryStatuses=["new","contacted","confirmed","completed","cancelled"] as const;
const outletStatuses=["new","contacted","interested","approved","rejected"] as const;
async function admin(){if(!(await getActiveAdmin()))throw new Error("Unauthorized");}
const id=z.string().uuid();
export async function listRequests(tab:string,input:Record<string,string|undefined>,paginate=true){await admin();const factory=tab!=="outlets";const q=(input.q??"").trim().slice(0,100), statuses=factory?factoryStatuses:outletStatuses, status=z.enum(["all",...statuses]).catch("all").parse(input.status??"all"),page=Math.max(1,Number(input.page)||1), table=factory?"factory_visit_requests":"furniture_outlet_enquiries";let query=createAdminClient().from(table).select("*",{count:"exact"}).order("created_at",{ascending:false});if(q)query=factory?query.or(`name.ilike.%${q}%,phone.ilike.%${q}%,email.ilike.%${q}%,location.ilike.%${q}%`):query.or(`person_name.ilike.%${q}%,phone.ilike.%${q}%,email.ilike.%${q}%,location.ilike.%${q}%,showroom_name.ilike.%${q}%`);if(status!=="all")query=query.eq("status",status);if(paginate)query=query.range((page-1)*20,page*20-1);const {data,error,count}=await query;if(error)throw new Error("Unable to load requests.");return {rows:data??[],count:count??0,q,status,page,factory};}
export async function getRequest(tab:string,value:string){await admin();const {data,error}=await createAdminClient().from(tab==="outlets"?"furniture_outlet_enquiries":"factory_visit_requests").select("*").eq("id",id.parse(value)).maybeSingle();if(error||!data)throw new Error("Request not found.");return data;}
export async function updateRequest(form:FormData){await admin();const tab=form.get("tab")==="outlets"?"outlets":"factory", statuses=tab==="outlets"?outletStatuses:factoryStatuses, value=z.object({id,status:z.enum(statuses),admin_notes:z.string().trim().max(1000).optional()}).parse(Object.fromEntries(form));const {error}=await createAdminClient().from(tab==="outlets"?"furniture_outlet_enquiries":"factory_visit_requests").update({status:value.status,admin_notes:value.admin_notes||null}).eq("id",value.id);if(error)throw new Error("Unable to update request.");revalidatePath("/admin/requests");revalidatePath(`/admin/requests/${tab==="outlets"?"outlet-enquiries":"factory-visits"}/${value.id}`);}
export async function exportRequests(tab:string,input:Record<string,string|undefined>){const d=await listRequests(tab,input,false),h=d.factory?"Name,Phone,Email,Location,Preferred Date,Interest,Status,Submitted":"Contact,Phone,Email,Outlet,Location,Size,Status,Submitted";const rows=d.rows.map((r:any)=>(d.factory?[r.name,r.phone,r.email,r.location,r.preferred_date,r.furniture_interest,r.status,r.created_at]:[r.person_name,r.phone,r.email,r.showroom_name,r.location,r.showroom_size_sqft,r.status,r.created_at]).map(escapeCsvValue).map((v:string)=>`\"${v}\"`).join(","));return `${h}\n${rows.join("\n")}`;}
export const requestOptions={factory:factoryStatuses,outlets:outletStatuses};
