-- Woodbay Batch 0: schema, indexes, RLS, and safe admin authorization.
create extension if not exists pgcrypto;
create schema if not exists private;

create type public.admin_role as enum ('super_admin', 'admin', 'editor');
create type public.content_status as enum ('draft', 'published', 'archived');
create type public.dealer_status as enum ('pending', 'active', 'inactive');
create type public.enquiry_status as enum ('new', 'contacted', 'approved', 'rejected');
create type public.furniture_enquiry_status as enum ('new', 'contacted', 'interested', 'approved', 'rejected');
create type public.visit_status as enum ('new', 'contacted', 'confirmed', 'completed', 'cancelled');
create type public.voucher_status as enum ('available', 'redeemed', 'disabled');
create type public.verification_result as enum ('valid', 'invalid', 'already_redeemed', 'disabled');

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = timezone('utc', now()); return new; end; $$;

create table public.admin_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, full_name text not null, role public.admin_role not null default 'editor', is_active boolean not null default true, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create or replace function private.is_active_admin() returns boolean language sql stable security definer set search_path = public, auth as $$ select exists (select 1 from public.admin_profiles where user_id = (select auth.uid()) and is_active) $$;
alter function private.is_active_admin() owner to postgres;
revoke all on function private.is_active_admin() from public;
grant execute on function private.is_active_admin() to authenticated;

create table public.product_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, parent_id uuid references public.product_categories(id) on delete set null, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.products (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.product_categories(id) on delete restrict, name text not null, slug text not null unique, short_description text, description text, product_code text, status public.content_status not null default 'draft', is_featured boolean not null default false, sort_order integer not null default 0, seo_title text, seo_description text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, storage_key text not null, alt_text text, sort_order integer not null default 0, is_primary boolean not null default false, created_at timestamptz not null default timezone('utc', now()));
create unique index product_images_one_primary_per_product on public.product_images(product_id) where is_primary;
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, sku text, dimension text, finish text, metadata jsonb not null default '{}'::jsonb, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.colours (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, hex_value text, storage_key text, colour_group text, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.projects (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, category text not null, location text, description text, featured_image text, status public.content_status not null default 'draft', sort_order integer not null default 0, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.project_images (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, storage_key text not null, alt_text text, sort_order integer not null default 0, created_at timestamptz not null default timezone('utc', now()));
create table public.dealers (id uuid primary key default gen_random_uuid(), business_name text not null, slug text not null unique, contact_person text, phone text not null, email text, state text not null, district text not null, area text, address text not null, google_maps_url text, latitude numeric(10,7), longitude numeric(10,7), payment_qr_image text, shop_image text, status public.dealer_status not null default 'pending', is_visible boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.dealer_applications (id uuid primary key default gen_random_uuid(), business_name text not null, contact_person text not null, phone text not null, email text, state text not null, district text not null, location text not null, address text, message text, status public.enquiry_status not null default 'new', admin_notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.furniture_outlet_enquiries (id uuid primary key default gen_random_uuid(), person_name text not null, showroom_name text, phone text not null, email text, location text not null, district text, showroom_size_sqft integer check (showroom_size_sqft > 0), message text, status public.furniture_enquiry_status not null default 'new', admin_notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.factory_visit_requests (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, email text, location text, preferred_date date, furniture_interest text, message text, status public.visit_status not null default 'new', admin_notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.voucher_codes (id uuid primary key default gen_random_uuid(), code text not null unique, product_id uuid references public.products(id) on delete set null, batch_reference text, serial_number text, status public.voucher_status not null default 'available', redeemed_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), check ((status = 'redeemed') = (redeemed_at is not null)));
create table public.voucher_redemptions (id uuid primary key default gen_random_uuid(), voucher_id uuid not null unique references public.voucher_codes(id) on delete restrict, customer_name text not null, phone text not null, location text, district text not null, dealer_name text not null, distributor_name text, redeemed_at timestamptz not null default timezone('utc', now()), created_at timestamptz not null default timezone('utc', now()));
create table public.voucher_verification_logs (id uuid primary key default gen_random_uuid(), entered_code text not null, voucher_id uuid references public.voucher_codes(id) on delete set null, result public.verification_result not null, created_at timestamptz not null default timezone('utc', now()));
create table public.downloads (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, category text, description text, file_path text not null, thumbnail text, status public.content_status not null default 'draft', sort_order integer not null default 0, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.blog_posts (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, excerpt text, content text, featured_image text, category text, status public.content_status not null default 'draft', published_at timestamptz, seo_title text, seo_description text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.contact_enquiries (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, email text, subject text, message text not null, status public.enquiry_status not null default 'new', admin_notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.seo_pages (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, h1 text not null, hero_content text, content text not null, meta_title text not null, meta_description text not null, faq_data jsonb, status public.content_status not null default 'draft', created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.site_settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null, is_public boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));

create index products_category_idx on public.products(category_id); create index products_status_idx on public.products(status); create index dealers_state_idx on public.dealers(state); create index dealers_district_idx on public.dealers(district); create index dealers_visible_idx on public.dealers(is_visible) where is_visible; create index voucher_codes_status_idx on public.voucher_codes(status); create index projects_status_idx on public.projects(status); create index blog_posts_status_idx on public.blog_posts(status); create index dealer_applications_status_created_idx on public.dealer_applications(status, created_at desc); create index furniture_enquiries_status_created_idx on public.furniture_outlet_enquiries(status, created_at desc); create index factory_visits_status_created_idx on public.factory_visit_requests(status, created_at desc); create index contact_enquiries_status_created_idx on public.contact_enquiries(status, created_at desc);

do $$ declare tbl text; begin foreach tbl in array array['admin_profiles','product_categories','products','product_variants','colours','projects','dealers','dealer_applications','furniture_outlet_enquiries','factory_visit_requests','voucher_codes','downloads','blog_posts','contact_enquiries','seo_pages','site_settings'] loop execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', tbl || '_updated_at', tbl); end loop; end $$;

-- RLS: public reads only explicitly public content. No direct public write access.
do $$ declare tbl text; begin foreach tbl in array array['admin_profiles','product_categories','products','product_images','product_variants','colours','projects','project_images','dealers','dealer_applications','furniture_outlet_enquiries','factory_visit_requests','voucher_codes','voucher_redemptions','voucher_verification_logs','downloads','blog_posts','contact_enquiries','seo_pages','site_settings'] loop execute format('alter table public.%I enable row level security', tbl); execute format('create policy "active admins manage %I" on public.%I for all to authenticated using ((select private.is_active_admin())) with check ((select private.is_active_admin()))', tbl, tbl); end loop; end $$;
create policy "users read their own admin profile" on public.admin_profiles for select to authenticated using (user_id = (select auth.uid()));
create policy "public reads active categories" on public.product_categories for select to anon, authenticated using (is_active);
create policy "public reads published products" on public.products for select to anon, authenticated using (status = 'published');
create policy "public reads images of published products" on public.product_images for select to anon, authenticated using (exists (select 1 from public.products p where p.id = product_id and p.status = 'published'));
create policy "public reads active variants of published products" on public.product_variants for select to anon, authenticated using (is_active and exists (select 1 from public.products p where p.id = product_id and p.status = 'published'));
create policy "public reads active colours" on public.colours for select to anon, authenticated using (is_active);
create policy "public reads published projects" on public.projects for select to anon, authenticated using (status = 'published');
create policy "public reads images of published projects" on public.project_images for select to anon, authenticated using (exists (select 1 from public.projects p where p.id = project_id and p.status = 'published'));
create policy "public reads active visible dealers" on public.dealers for select to anon, authenticated using (status = 'active' and is_visible);
create policy "public reads published downloads" on public.downloads for select to anon, authenticated using (status = 'published');
create policy "public reads published blogs" on public.blog_posts for select to anon, authenticated using (status = 'published');
create policy "public reads published seo pages" on public.seo_pages for select to anon, authenticated using (status = 'published');
create policy "public reads public settings" on public.site_settings for select to anon, authenticated using (is_public);

-- Keep all voucher master, redemption, and verification-log access server/admin-only.
revoke all on all tables in schema public from anon;
grant select on public.product_categories, public.products, public.product_images, public.product_variants, public.colours, public.projects, public.project_images, public.dealers, public.downloads, public.blog_posts, public.seo_pages, public.site_settings to anon, authenticated;
grant all on all tables in schema public to service_role;
